Kalendarz/Kalendarz/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalendarz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}

Kalendarz/Kalendarz/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'D:\Próby\Kalendarz\Kalendarz\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Kalendarz/Kalendarz/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Kalendarz/Kalendarz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kalendarz.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Kalendarz/Kalendarz/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Kalendarz.Models;

namespace Kalendarz.Controllers
{
    public class LogController : Controller
    {
        // GET: Log
        DBModels db = new DBModels();
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(User user)
        {
            var userDetail = db.User.Where(x => x.Email == user.Email && x.Haslo == user.Haslo).Count();
            if(userDetail>0)
            {
                return RedirectToAction("Dashborad");
            }
            else
            {
                return RedirectToAction("Dashborad2");
            }
        }

        public ActionResult Dashborad()
        {
            return View();
        }

        public ActionResult Dashborad2()
        {
            return View();
        }
    }
}

Kalendarz/Kalendarz/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kalendarz.Models;

namespace Kalendarz.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult AddOrEdit(int id=0)
        {
            User user = new User();
            return View();
        }

        [HttpPost]
        public ActionResult AddOrEdit(User user)
        {
            using(DBModels db=new DBModels())
            {
                if (db.User.Any(x => x.Email == user.Email))
                {
                    ViewBag.DuplicateMessage = "Użytkownik już istnieje.";
                    return View("AddOrEdit", user);
                }
                else
                {
                    db.User.Add(user);
                    db.SaveChanges();
                }
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Rejestracja zakończona pomyślnie.";
            return View("AddOrEdit",new User());
        }
    }
}

Kalendarz/Kalendarz/Views/Home/About.cshtml
@{
    ViewBag.Title = "O projekcie";
}
<h2>@ViewBag.Title.</h2>

<p><p>
    Nasz projekt ma na celu stworzenie aplikacji kalendarza z możliwością dodawania wydarzeń, planów, deadlinów, celów, zadań itp. Użytkownikowi zostanie udostępniony program, który pozwoli na uporządkowanie i zaplanowanie dni, tygodni, miesięcy i lat tak, aby o niczym nie zapomniał i produktywnie dysponował swoim czasem.

    Funkcje związane z grupowaniem wydarzeń oraz wyświetlaniem zapisanych planów w formie listy to-do pomogą użytkownikowi kontrolować pracę nad własnymi projektami, a kalendarzowy widok z kolorystycznym zaznaczeniem pozwoli dostrzec większy obraz nadchodzących dni. Możliwości włączenia widocznego licznika dni pozostałych do danego wydarzenia lub deadlinu pomogą nie zapomnieć o tym, co priorytetowe (jak np. termin spłaty raty kredytu czy oddania projektu na inżynierię oprogramowania).

    Nasz kalendarz będzie aplikacją webową, napisaną w C# z ASP.NET, wykorzystującą także bazę danych przechowującą m.in. dodane przez użytkownika wydarzenia lub cele. Pozwoli to dostać się do swoich planów i listy obowiązków z większości urządzeń z dostępem do internetu, wliczając w to urządzenia mobilne.

</p></p>

Kalendarz/Kalendarz/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt z twórcami";
}
<h2>@ViewBag.Title.</h2>

<address>
    <strong>Adam Ch.:</strong>   <a href="mailto:ulcostam@edu.uni.lodz.pl">ulcostam@edu.uni.lodz.pl</a><br />
    <strong>Weronika K.:</strong> <a href="mailto:ulcostam@edu.uni.lodz.pl">ulcostam@edu.uni.lodz.pl</a><br />
    <strong>Joanna J.:</strong> <a href="mailto:ulcostam@edu.uni.lodz.pl">ulcostam@edu.uni.lodz.pl</a>
</address>

Kalendarz/Kalendarz/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Rejestracja i logowanie";
}
<h2>@ViewBag.Title.</h2>

<p><p>Kliknij <a href="https://localhost:44325/User/AddOrEdit">tutaj </a>aby się zarejestrować lub <a href="https://localhost:44325/Log/Index">tutaj </a>aby się zalogować.</p></p>

Kalendarz/Kalendarz/Views/Log/Dashborad.cshtml
@{
    ViewBag.Title = "Logowanie";
}

<h1>Zalogowano.</h1>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Wyloguj" class="btn btn-default" />
    </div>
</div>

Kalendarz/Kalendarz/Views/Log/Dashborad2.cshtml
@{
    ViewBag.Title = "Logowanie";
}

<h2>Logowanie nie powiodło się.</h2>

Kalendarz/Kalendarz/Views/Log/Index.cshtml
@model Kalendarz.Models.User

@{
    ViewBag.Title = "Index";
}

<h2>Loguj</h2>


@using (Html.BeginForm("Index", "Log", FormMethod.Post))
{ 
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Haslo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Haslo, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zaloguj" class="btn btn-default" />
        </div>
    </div>

</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kalendarz/Kalendarz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nazwa aplikacji", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rejestracja i logowanie", "Index", "Home")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Moja aplikacja ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Kalendarz/Kalendarz/Views/User/AddOrEdit.cshtml
@model Kalendarz.Models.User

@{
    ViewBag.Title = "Rejestracja użytkownika";
}

<h2>Rejestracja użytkownika</h2>


@using (Html.BeginForm("AddOrEdit","User",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Haslo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Haslo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Haslo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PotwierdzHaslo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PotwierdzHaslo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PotwierdzHaslo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Utwórz" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class=" label-success">@ViewBag.SuccessMessage</label>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class=" label-default">@ViewBag.DuplicateMessage</label>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}